apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "bank-rag.fullname" . } }-langchain
spec:
  replicas: { { .Values.langchain.replicaCount } }
  selector:
    matchLabels:
      app: langchain
  template:
    metadata:
      labels:
        app: langchain
    spec:
      containers:
        - name: langchain
          image: { { .Values.langchain.image } }
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: ENVIRONMENT
              value: { { .Values.global.environment | quote } }
            - name: OTEL_ENABLED
              value: { { ternary "true" "false" .Values.global.otel.enabled | quote } }
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: { { .Values.global.otel.endpoint | quote } }
          - name: QDRANT_URL
            value: "http://qdrant:6333"

---
apiVersion: v1
kind: Service
metadata:
  name: langchain
spec:
  type: { { .Values.langchain.service.type } }
  selector:
    app: langchain
  ports:
    - name: http
      port: { { .Values.langchain.service.port } }
      targetPort: 3001
